"""PHANTOM Report generator — assembles the signed evidence bundle + narrative.

For each confirmed (or suspected) suspicious cluster, this module builds:
  1. RingMember list — applicant snapshot of each ring participant
  2. EvidenceBundle — every score, every component, every timestamp
  3. Ed25519 signature over canonical JSON of the bundle
  4. Origin / timing / narrative paragraphs for the UI

The narrative is delegated to services/narrative_writer which tries Gemini
Flash (if GEMINI_API_KEY is set) and falls back to a deterministic
f-string template. The demo path never depends on the LLM.
"""
from __future__ import annotations

import hashlib
from datetime import datetime
from uuid import UUID

from loguru import logger

from crypto.signer import get_signer
from schemas.origin_certificate import OriginCertificate
from schemas.phantom_report import (
    EvidenceBundle,
    PHANTOMReport,
    RecommendedAction,
    RingMember,
)
from services.cross_signal_engine import ClusterVerdict
from services.narrative_writer import build_narrative


def _ring_id_from_members(member_ids: list[UUID]) -> str:
    """Deterministic ring id — same set of members always produces same id."""
    joined = "|".join(sorted(str(m) for m in member_ids))
    return "RING-" + hashlib.sha256(joined.encode()).hexdigest()[:12].upper()


def _build_members(
    member_ids: list[UUID],
    applicants_by_id: dict[UUID, dict],
    certificates_by_app: dict[UUID, OriginCertificate],
) -> list[RingMember]:
    members: list[RingMember] = []
    for mid in member_ids:
        app = applicants_by_id.get(mid)
        if app is None:
            continue
        cert = certificates_by_app.get(mid)
        members.append(
            RingMember(
                application_id=mid,
                applicant_name=app["applicant_name"],
                city=app["city"],
                loan_amount_inr=int(app["loan_amount_inr"]),
                submission_time=app["submission_time"],
                cbs_match_score=cert.cbs_match_score if cert else 0.0,
                origin_tool=cert.origin_tool if cert else "Unknown",
                font_subset_hash=cert.font_subset_hash if cert else "",
            )
        )
    return members


def _doc_creation_window(certs: list[OriginCertificate]) -> tuple[datetime | None, datetime | None]:
    times = [c.creation_timestamp for c in certs if c.creation_timestamp]
    if not times:
        return None, None
    return min(times), max(times)


def _fmt_inr(amount: int) -> str:
    """Format an INR amount in Indian numbering ('₹6.20 Cr', '₹52.50 L')."""
    if amount >= 10_000_000:  # 1 crore = 1e7
        return f"INR {amount / 10_000_000:.2f} Cr"
    if amount >= 100_000:
        return f"INR {amount / 100_000:.2f} L"
    return f"INR {amount:,}"


def _origin_summary(verdict: ClusterVerdict, members: list[RingMember]) -> str:
    n = len(members)
    if not members:
        return "No members to summarize."

    # Pick the dominant origin tool by frequency.
    from collections import Counter
    tools = Counter(m.origin_tool for m in members if m.origin_tool).most_common(1)
    dominant_tool = tools[0][0] if tools else "Unknown"
    dominant_count = tools[0][1] if tools else 0

    tool_frac_pct = round(verdict.same_tool_fraction * 100)
    font_frac_pct = round(verdict.font_hash_match_fraction * 100)

    return (
        f"All {n} documents in this cluster were generated by "
        f"'{dominant_tool}' ({dominant_count}/{n} = {tool_frac_pct}% match) "
        f"with {font_frac_pct}% sharing the same font fingerprint. "
        f"Mean entropy-profile similarity across the cluster: {verdict.entropy_similarity:.2f}."
    )


def _timing_summary(
    verdict: ClusterVerdict, doc_from: datetime | None, doc_to: datetime | None
) -> str:
    sub_from = verdict.submissions_from
    sub_to = verdict.submissions_to
    bits: list[str] = []

    if doc_from and doc_to:
        delta = doc_to - doc_from
        bits.append(
            f"Documents created between {doc_from:%Y-%m-%d %H:%M} and "
            f"{doc_to:%H:%M} ({int(delta.total_seconds() / 60)}-minute window)"
        )

    if isinstance(sub_from, datetime) and isinstance(sub_to, datetime):
        sub_delta = sub_to - sub_from
        bits.append(
            f"Applications submitted between {sub_from:%H:%M} and {sub_to:%H:%M} "
            f"({int(sub_delta.total_seconds() / 60)}-minute window)"
        )

    return " | ".join(bits) if bits else "Timing data unavailable."




def generate_report(
    verdict: ClusterVerdict,
    *,
    applicants_by_id: dict[UUID, dict],
    certificates_by_app: dict[UUID, OriginCertificate],
) -> PHANTOMReport:
    """Build a signed PHANTOMReport from a cluster verdict + supporting data."""
    if verdict.recommended_action == RecommendedAction.CLEAR:
        # Defensive: we shouldn't be generating reports for cleared clusters,
        # but if a caller does, we still produce a coherent (non-alarming) doc.
        logger.debug("Generating report for CLEAR cluster (informational only)")

    member_ids = verdict.member_ids
    ring_id = _ring_id_from_members(member_ids)
    members = _build_members(member_ids, applicants_by_id, certificates_by_app)
    member_certs = [certificates_by_app[m] for m in member_ids if m in certificates_by_app]
    doc_from, doc_to = _doc_creation_window(member_certs)

    bundle = EvidenceBundle(
        ring_id=ring_id,
        detected_at=datetime.utcnow(),
        members=members,
        behavioral_score=verdict.behavioral_score,
        origin_match_score=verdict.origin_match_score,
        phantom_score=verdict.phantom_score,
        timing_burst_score=verdict.timing_burst_score,
        template_match_fraction=verdict.template_match_fraction,
        cluster_size_score=verdict.cluster_size_score,
        same_tool_fraction=verdict.same_tool_fraction,
        entropy_similarity=verdict.entropy_similarity,
        font_hash_match_fraction=verdict.font_hash_match_fraction,
        pii_overlap_fraction=verdict.pii_overlap_fraction,
        text_similarity_fraction=verdict.text_similarity_fraction,
        name_similarity_fraction=verdict.name_similarity_fraction,
        documents_created_from=doc_from,
        documents_created_to=doc_to,
        submissions_from=verdict.submissions_from,
        submissions_to=verdict.submissions_to,
    )

    # Sign
    signer = get_signer()
    signed = signer.sign(bundle.model_dump(mode="json"))

    origin_sum = _origin_summary(verdict, members)
    timing_sum = _timing_summary(verdict, doc_from, doc_to)
    narrative = build_narrative(verdict, members, origin_sum, timing_sum)

    total_exposure = sum(m.loan_amount_inr for m in members)

    report = PHANTOMReport(
        ring_id=ring_id,
        ring_size=len(members),
        total_exposure_inr=total_exposure,
        phantom_confidence_pct=round(verdict.phantom_score * 100, 2),
        evidence_bundle=bundle,
        evidence_hash_sha256=signed.sha256_hex,
        evidence_signature_ed25519=signed.signature_b64,
        signing_key_id=signed.signing_key_id,
        origin_summary=origin_sum,
        timing_summary=timing_sum,
        narrative=narrative,
        recommended_action=verdict.recommended_action,
    )

    logger.info(
        "Report generated | ring={} | size={} | exposure={} | conf={}% | key_id={}",
        ring_id,
        report.ring_size,
        _fmt_inr(total_exposure),
        report.phantom_confidence_pct,
        signed.signing_key_id,
    )
    return report
