"""Factory that produces CBS-style and Canva-style synthetic PDFs.

Shared by seed/build_cbs_corpus.py (which makes 100 CBS-style PDFs for the
reference centroid) and demo_data/generate_demo.py (which makes 40 demo PDFs,
11 of them deliberately Canva-style).

The two styles must look DIFFERENT enough that their entropy + ViT
fingerprints discriminate cleanly:

  CBS style    →  dense tabular layout, multiple font weights, monochrome,
                  bank header with branch/IFSC footer, subsetted fonts
  Canva style  →  centered hero heading, single embedded font, decorative
                  color blocks, simple structure, NO font subsetting
"""
from __future__ import annotations

import io
import random
from dataclasses import dataclass
from datetime import datetime, timedelta

import pikepdf
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

# --- Fonts -----------------------------------------------------------------
# CBS PDFs use a TTF that ReportLab embeds + subsets automatically (subset
# prefix shows up in PDF font name). Canva fakes use built-in Helvetica which
# is one of the 14 PDF standard fonts — NOT embedded, NOT subsetted.

_CBS_FONT_NAME = "CBSSans"
_CBS_FONT_BOLD = "CBSSansBold"
_FONTS_REGISTERED = False


def _register_cbs_fonts() -> None:
    """Register a TTF font that ReportLab will embed + subset.

    Uses a Windows system font as the source. Falls back to Helvetica if no
    TTF is found — in that case the CBS PDFs lose the subset signal, but the
    other signals (producer, entropy) still discriminate.
    """
    global _FONTS_REGISTERED
    if _FONTS_REGISTERED:
        return

    candidates = [
        # Windows
        (r"C:\Windows\Fonts\arial.ttf", r"C:\Windows\Fonts\arialbd.ttf"),
        (r"C:\Windows\Fonts\calibri.ttf", r"C:\Windows\Fonts\calibrib.ttf"),
        (r"C:\Windows\Fonts\verdana.ttf", r"C:\Windows\Fonts\verdanab.ttf"),
        # Linux (Docker)
        ("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
         "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"),
        ("/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
         "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"),
    ]

    import os

    for regular, bold in candidates:
        if os.path.exists(regular) and os.path.exists(bold):
            pdfmetrics.registerFont(TTFont(_CBS_FONT_NAME, regular))
            pdfmetrics.registerFont(TTFont(_CBS_FONT_BOLD, bold))
            _FONTS_REGISTERED = True
            return

    # Fall back silently — CBS PDFs will use Helvetica too. Producer string
    # alone will still distinguish them from Canva fakes.
    _FONTS_REGISTERED = True


# --- CBS-style salary slip --------------------------------------------------


@dataclass
class SalarySlipData:
    employee_name: str
    employee_id: str
    designation: str
    period: str           # "January 2024"
    branch_name: str
    branch_ifsc: str
    bank_name: str        # for the PDF header
    basic_pay: int
    hra: int
    da: int
    special_allowance: int
    pf_deduction: int
    professional_tax: int
    income_tax: int
    net_pay: int
    account_number: str


def _draw_cbs_header(c: canvas.Canvas, slip: SalarySlipData, font_main: str, font_bold: str) -> None:
    page_w, page_h = A4

    # Top bar — solid dark band, monochrome
    c.setFillColor(HexColor("#1F2937"))
    c.rect(0, page_h - 28 * mm, page_w, 28 * mm, fill=1, stroke=0)

    c.setFillColor(HexColor("#FFFFFF"))
    c.setFont(font_bold, 16)
    c.drawString(15 * mm, page_h - 15 * mm, slip.bank_name)
    c.setFont(font_main, 9)
    c.drawString(15 * mm, page_h - 22 * mm, f"Branch: {slip.branch_name}   IFSC: {slip.branch_ifsc}")

    c.setFont(font_main, 9)
    c.drawRightString(page_w - 15 * mm, page_h - 15 * mm, "INTERNAL DOCUMENT")
    c.drawRightString(page_w - 15 * mm, page_h - 22 * mm, "Generated by Core Banking System")


def _draw_cbs_table(c: canvas.Canvas, slip: SalarySlipData, font_main: str, font_bold: str) -> None:
    page_w, page_h = A4

    c.setFillColor(HexColor("#000000"))
    c.setFont(font_bold, 14)
    c.drawString(15 * mm, page_h - 45 * mm, "SALARY STATEMENT")

    c.setFont(font_main, 10)
    info_y = page_h - 58 * mm
    info = [
        ("Employee Name", slip.employee_name),
        ("Employee ID", slip.employee_id),
        ("Designation", slip.designation),
        ("Pay Period", slip.period),
        ("Bank Account", slip.account_number),
    ]
    for label, value in info:
        c.setFont(font_bold, 9)
        c.drawString(15 * mm, info_y, f"{label}:")
        c.setFont(font_main, 10)
        c.drawString(60 * mm, info_y, str(value))
        info_y -= 6 * mm

    # Two-column earnings / deductions table — the visual signature.
    table_top = page_h - 100 * mm
    col_left = 15 * mm
    col_right = page_w / 2 + 5 * mm
    col_w = (page_w - 30 * mm) / 2 - 5 * mm

    c.setFillColor(HexColor("#E5E7EB"))
    c.rect(col_left, table_top, col_w, 8 * mm, fill=1, stroke=0)
    c.rect(col_right, table_top, col_w, 8 * mm, fill=1, stroke=0)
    c.setFillColor(HexColor("#000000"))
    c.setFont(font_bold, 10)
    c.drawString(col_left + 3 * mm, table_top + 2.5 * mm, "EARNINGS")
    c.drawString(col_right + 3 * mm, table_top + 2.5 * mm, "DEDUCTIONS")

    earnings = [
        ("Basic Pay", slip.basic_pay),
        ("HRA", slip.hra),
        ("DA", slip.da),
        ("Special Allowance", slip.special_allowance),
    ]
    deductions = [
        ("Provident Fund", slip.pf_deduction),
        ("Professional Tax", slip.professional_tax),
        ("Income Tax", slip.income_tax),
    ]

    c.setFont(font_main, 9)
    row_h = 7 * mm
    for i, (label, amount) in enumerate(earnings):
        y = table_top - (i + 1) * row_h
        c.drawString(col_left + 3 * mm, y + 2 * mm, label)
        c.drawRightString(col_left + col_w - 3 * mm, y + 2 * mm, f"INR {amount:,}")
        c.setStrokeColor(HexColor("#D1D5DB"))
        c.line(col_left, y, col_left + col_w, y)

    for i, (label, amount) in enumerate(deductions):
        y = table_top - (i + 1) * row_h
        c.drawString(col_right + 3 * mm, y + 2 * mm, label)
        c.drawRightString(col_right + col_w - 3 * mm, y + 2 * mm, f"INR {amount:,}")
        c.setStrokeColor(HexColor("#D1D5DB"))
        c.line(col_right, y, col_right + col_w, y)

    # Net pay strip
    net_y = table_top - (max(len(earnings), len(deductions)) + 2) * row_h
    c.setFillColor(HexColor("#1F2937"))
    c.rect(15 * mm, net_y, page_w - 30 * mm, 10 * mm, fill=1, stroke=0)
    c.setFillColor(HexColor("#FFFFFF"))
    c.setFont(font_bold, 11)
    c.drawString(18 * mm, net_y + 3 * mm, "NET PAYABLE")
    c.drawRightString(page_w - 18 * mm, net_y + 3 * mm, f"INR {slip.net_pay:,}")


def _draw_cbs_footer(c: canvas.Canvas, slip: SalarySlipData, font_main: str) -> None:
    page_w, _ = A4
    c.setFillColor(HexColor("#6B7280"))
    c.setFont(font_main, 7)
    c.drawString(15 * mm, 12 * mm, "This is a system-generated document and does not require signature.")
    c.drawRightString(page_w - 15 * mm, 12 * mm, f"Page 1 of 1   |   IFSC {slip.branch_ifsc}")


def build_cbs_pdf(slip: SalarySlipData) -> bytes:
    """Render a CBS-style salary slip and return raw PDF bytes (no metadata yet)."""
    _register_cbs_fonts()

    if _CBS_FONT_NAME in pdfmetrics.getRegisteredFontNames():
        font_main = _CBS_FONT_NAME
        font_bold = _CBS_FONT_BOLD
    else:
        font_main = "Helvetica"
        font_bold = "Helvetica-Bold"

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    _draw_cbs_header(c, slip, font_main, font_bold)
    _draw_cbs_table(c, slip, font_main, font_bold)
    _draw_cbs_footer(c, slip, font_main)
    c.showPage()
    c.save()
    return buf.getvalue()


# --- Canva-style fake salary slip ------------------------------------------


@dataclass
class CanvaSlipData:
    employee_name: str
    designation: str
    period: str
    company_name: str
    basic_pay: int
    allowances: int
    deductions: int
    net_pay: int
    account_number: str


def build_canva_pdf(slip: CanvaSlipData) -> bytes:
    """Render a Canva-style salary slip. Single font, decorative, no subsetting."""
    page_w, page_h = A4
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)

    # Big decorative color bar across the top
    c.setFillColor(HexColor("#7C3AED"))
    c.rect(0, page_h - 60 * mm, page_w, 60 * mm, fill=1, stroke=0)
    c.setFillColor(HexColor("#FFFFFF"))
    c.setFont("Helvetica-Bold", 28)
    c.drawCentredString(page_w / 2, page_h - 30 * mm, "SALARY SLIP")
    c.setFont("Helvetica", 14)
    c.drawCentredString(page_w / 2, page_h - 45 * mm, slip.company_name)

    # Employee block
    c.setFillColor(HexColor("#1F2937"))
    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(page_w / 2, page_h - 80 * mm, slip.employee_name)
    c.setFont("Helvetica", 11)
    c.drawCentredString(page_w / 2, page_h - 90 * mm, slip.designation)
    c.drawCentredString(page_w / 2, page_h - 98 * mm, f"For the month of {slip.period}")

    # Stat boxes
    box_y = page_h - 130 * mm
    box_w = (page_w - 60 * mm) / 3
    boxes = [
        ("BASIC PAY", slip.basic_pay, "#10B981"),
        ("ALLOWANCES", slip.allowances, "#F59E0B"),
        ("DEDUCTIONS", slip.deductions, "#EF4444"),
    ]
    for i, (label, amount, color) in enumerate(boxes):
        x = 20 * mm + i * (box_w + 5 * mm)
        c.setFillColor(HexColor(color))
        c.rect(x, box_y, box_w, 30 * mm, fill=1, stroke=0)
        c.setFillColor(HexColor("#FFFFFF"))
        c.setFont("Helvetica-Bold", 9)
        c.drawCentredString(x + box_w / 2, box_y + 22 * mm, label)
        c.setFont("Helvetica-Bold", 14)
        c.drawCentredString(x + box_w / 2, box_y + 12 * mm, f"INR {amount:,}")

    # Net pay big number
    c.setFillColor(HexColor("#1F2937"))
    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(page_w / 2, box_y - 25 * mm, "NET PAY")
    c.setFont("Helvetica-Bold", 32)
    c.setFillColor(HexColor("#7C3AED"))
    c.drawCentredString(page_w / 2, box_y - 45 * mm, f"INR {slip.net_pay:,}")

    # Footer
    c.setFillColor(HexColor("#9CA3AF"))
    c.setFont("Helvetica", 8)
    c.drawCentredString(page_w / 2, 15 * mm, f"Account: {slip.account_number}   |   {slip.company_name}")

    c.showPage()
    c.save()
    return buf.getvalue()


# --- Metadata injection -----------------------------------------------------


def inject_pdf_metadata(
    raw_pdf: bytes,
    *,
    producer: str,
    creator: str,
    creation_date: datetime,
) -> bytes:
    """Overwrite /Producer, /Creator, /CreationDate, /ModDate in PDF docinfo.

    ReportLab stamps its own producer string. To make a PDF look like it came
    from Canva or Finacle, we post-process the bytes through pikepdf and
    replace the docinfo fields. The actual rendered content is unchanged.
    """
    out = io.BytesIO()
    pdf_date = creation_date.strftime("D:%Y%m%d%H%M%S")

    with pikepdf.open(io.BytesIO(raw_pdf)) as pdf:
        pdf.docinfo["/Producer"] = producer
        pdf.docinfo["/Creator"] = creator
        pdf.docinfo["/CreationDate"] = pdf_date
        pdf.docinfo["/ModDate"] = pdf_date
        pdf.save(out)

    return out.getvalue()


# --- Sample data generation -------------------------------------------------

_CBS_FIRST_NAMES = [
    "Arjun", "Meera", "Vikrant", "Ananya", "Karthik", "Pooja", "Tushar",
    "Lakshmi", "Rohan", "Aishwarya", "Nitin", "Shruti", "Aditya", "Divya",
    "Harsha", "Ishita", "Vivek", "Sangeeta", "Prakash", "Neha", "Saurabh",
    "Priyanka", "Arnav", "Sonal", "Rakesh", "Tanvi", "Mohit", "Ramesh",
    "Tarun", "Bhavna",
]
_CBS_LAST_NAMES = [
    "Krishnan", "Pillai", "Singh", "Iyengar", "Rao", "Bansal", "Shah",
    "Subramanian", "Banerjee", "Menon", "Agarwal", "Kapoor", "Reddy", "Nair",
    "Vardhan", "Chatterjee", "Malhotra", "Verma", "Joshi", "Tiwari", "Gupta",
    "Sinha", "Bhatia", "Modi", "Bhat", "Aggarwal", "Chandran", "Kumar", "Saxena",
]
_DESIGNATIONS = [
    "Senior Software Engineer", "Branch Manager", "Operations Head",
    "Project Manager", "Technical Architect", "Cluster Manager",
    "Senior Consultant", "VP - Operations", "Regional Head",
]
_BANK_PROFILES = [
    ("State Bank of India", "SBIN", "Finacle 7.3", "Finacle Report Engine"),
    ("HDFC Bank", "HDFC", "TCS BaNCS 9.1", "BaNCS Statement Engine"),
    ("ICICI Bank", "ICIC", "Oracle FLEXCUBE 12.4", "FLEXCUBE Document Service"),
    ("Axis Bank", "AXIS", "Temenos T24", "T24 Reporter"),
]
_BRANCH_NAMES = [
    "Whitefield", "Andheri East", "Kakkanad", "Salt Lake", "Indiranagar",
    "Gachibowli", "DLF Phase 3", "Satellite", "Adyar", "Madhapur", "JP Nagar",
]


def generate_cbs_corpus_data(n: int = 100, seed: int = 42) -> list[tuple[SalarySlipData, dict]]:
    """Generate (slip, metadata_kwargs) tuples for the CBS reference corpus."""
    rng = random.Random(seed)
    results: list[tuple[SalarySlipData, dict]] = []
    base_date = datetime(2023, 9, 1, 9, 0, 0)

    for i in range(n):
        first = rng.choice(_CBS_FIRST_NAMES)
        last = rng.choice(_CBS_LAST_NAMES)
        bank_name, ifsc_prefix, producer, creator = rng.choice(_BANK_PROFILES)

        basic = rng.randrange(40000, 120000, 1000)
        hra = int(basic * rng.uniform(0.30, 0.45))
        da = int(basic * rng.uniform(0.10, 0.20))
        special = rng.randrange(5000, 20000, 500)
        gross = basic + hra + da + special
        pf = int(basic * 0.12)
        ptax = 200
        itax = int(gross * rng.uniform(0.10, 0.18))
        net = gross - pf - ptax - itax

        slip = SalarySlipData(
            employee_name=f"{first} {last}",
            employee_id=f"EMP{rng.randrange(10000, 99999)}",
            designation=rng.choice(_DESIGNATIONS),
            period="January 2024",
            branch_name=rng.choice(_BRANCH_NAMES),
            branch_ifsc=f"{ifsc_prefix}0{rng.randrange(100000, 999999)}",
            bank_name=bank_name,
            basic_pay=basic,
            hra=hra,
            da=da,
            special_allowance=special,
            pf_deduction=pf,
            professional_tax=ptax,
            income_tax=itax,
            net_pay=net,
            account_number=str(rng.randrange(10**11, 10**12)),
        )
        meta = {
            "producer": producer,
            "creator": creator,
            "creation_date": base_date + timedelta(days=rng.randint(0, 90),
                                                    hours=rng.randint(0, 8),
                                                    minutes=rng.randint(0, 59)),
        }
        results.append((slip, meta))

    return results


def make_cbs_pdf_bytes(slip: SalarySlipData, *, producer: str, creator: str,
                        creation_date: datetime) -> bytes:
    """One-shot: render + inject metadata. Returns final PDF bytes."""
    raw = build_cbs_pdf(slip)
    return inject_pdf_metadata(raw, producer=producer, creator=creator,
                                creation_date=creation_date)
