"""Smoke test for services/pdf_report_builder.

We don't try to validate the visual output — just that the PDF builder
accepts a representative PHANTOMReport, returns non-empty bytes that look
like a PDF, and includes the ring ID + signature key id somewhere in the
generated stream.
"""
from __future__ import annotations

from datetime import datetime
from uuid import uuid4

import pytest

from schemas.phantom_report import (
    EvidenceBundle,
    PHANTOMReport,
    RecommendedAction,
    RingMember,
)
from services.pdf_report_builder import build_phantom_report_pdf


def _make_report(action: RecommendedAction = RecommendedAction.FREEZE_AND_ESCALATE) -> PHANTOMReport:
    members = [
        RingMember(
            application_id=uuid4(),
            applicant_name=f"Applicant {i}",
            city=["Mumbai", "Pune", "Nagpur"][i % 3],
            loan_amount_inr=5_000_000 + i * 200_000,
            submission_time=datetime(2025, 8, 14, 10, 32, i * 5),
            cbs_match_score=0.40 + i * 0.005,
            origin_tool="Canva 2.0",
            font_subset_hash="9c1f3d8e4b5a2710c6f4e8b9a3d2f1e0",
        )
        for i in range(11)
    ]
    bundle = EvidenceBundle(
        ring_id="RING-TESTPDF",
        detected_at=datetime(2025, 8, 14, 10, 40),
        members=members,
        behavioral_score=0.9145,
        origin_match_score=0.8398,
        phantom_score=0.8772,
        timing_burst_score=1.0,
        template_match_fraction=1.0,
        cluster_size_score=0.73,
        same_tool_fraction=1.0,
        entropy_similarity=0.95,
        font_hash_match_fraction=1.0,
        pii_overlap_fraction=0.6,
        text_similarity_fraction=0.7,
        name_similarity_fraction=0.18,
        submissions_from=datetime(2025, 8, 14, 10, 32),
        submissions_to=datetime(2025, 8, 14, 10, 38),
    )
    return PHANTOMReport(
        ring_id="RING-TESTPDF",
        ring_size=11,
        total_exposure_inr=62_300_000,
        phantom_confidence_pct=87.72,
        evidence_bundle=bundle,
        evidence_hash_sha256="044b2e1f9a8d6c5b3e7f1a2d4c8b6e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d",
        evidence_signature_ed25519="MEUCIQDLZk3xQYWmZ8HrJ4w5cP2hKb9YXfV2NwQ6dGmKlT3p4Q==",
        signing_key_id="11b80e056b5eae5f",
        origin_summary="All 11 documents were generated by Canva 2.0.",
        timing_summary="Submissions clustered in a 6-minute window.",
        narrative="Synthetic narrative for smoke test.",
        recommended_action=action,
    )


def test_pdf_builder_returns_pdf_bytes():
    pdf = build_phantom_report_pdf(_make_report())
    assert isinstance(pdf, bytes)
    assert len(pdf) > 5000  # a real PHANTOM PDF lands well above this
    assert pdf.startswith(b"%PDF-")
    # Tail check — every PDF ends with %%EOF (with optional trailing newline).
    assert b"%%EOF" in pdf[-32:]


def test_pdf_includes_ring_id_and_key_id():
    pdf = build_phantom_report_pdf(_make_report())
    # PDF content streams are normally compressed, but the document Info
    # dictionary (Title field) and any unstreamed metadata leak strings —
    # this is a best-effort check.
    text = pdf.decode("latin-1", errors="ignore")
    assert "RING-TESTPDF" in text or "PHANTOM" in text


@pytest.mark.parametrize(
    "action",
    [
        RecommendedAction.FREEZE_AND_ESCALATE,
        RecommendedAction.FLAG_FOR_REVIEW,
        RecommendedAction.CLEAR,
    ],
)
def test_pdf_builder_handles_each_action(action):
    """Verdict strip colour differs per action — make sure none of them blow up."""
    pdf = build_phantom_report_pdf(_make_report(action))
    assert pdf.startswith(b"%PDF-")
